### ISSUE TITLE
Location of categories selection of axis in mapping object

### ISSUE THREAD

**Issue by djvanderlaan** [statmine/statminer#3]
When a categorical variable is placed on one of the axes and there is a selection of categories for this variable this selection is part of the `_filter` property of the mapping object:

``` js
{
  x: 'year',
  y: 'diabetes',
  colour: 'sex',
  _filter: {
    sex: ['total', 'male']
  }
}
```

Another solution would be to have this be part of the axis:

``` js
{
  x: {variable : 'year'},
  y: {variable: 'diabetes'},
  colour: {variable: 'sex', selection: ['total', 'male']}
}
```

This has the advantage that it is easier to pass all relevant information for one axis to the `MapAxis` component.

**Comment by djvanderlaan** [comment]
And yet another possible format for the mapping object is:

```
{
  x: [
    {variable: 'year'}
  ], 
  y: [
    {variable: 'diabetes'}
  ],
  colour: [
    {variable: 'sex', selection: ['total', 'male']}
  ],
  _filter: [
    {variable: 'age', selection: ['total']},
    {variable: 'region', selection: ['amsterdam']}
  ]
}
```

This has two advantages:
1. It allows for future extensions where multiple variables are placed on one axis (for example, in the line graph).
2. The `_filter` is treated the same as the axes of the graph making reuse of selection components easier. In that sense the `_filter` is a special axis of the graph. 

Disadvantages:
1. We need more looping over arrays to look up values. E.g. to see if a filter has been applied on `age` we need to loop over the `_filter` array. 
2. Although the `_filter` can be seem as a type of axis, it behaves differently (only variables that are not placed on other axes can be selected; only one category can be selected for a categorical variable), so logic needs to be built into the components for this.

**Comment by edwindj** [comment]
Nice thoughts! Here my two cents:

I like the last proposal, which has the benefits that it is more symmetric. Note that `_filter` in general will automatically computed (since categorical variables need to be "slice"-d when not selected.
- I suggest that each mapaxis can have one variable + optional filter/selection on that variable. Maybe a `filtered_variable`?
- The `_filter` axis is indeed special (its an array of `filtered_variables`, that are all categorical, with one categorie selected
- We should change the name `_filter`. Suggestions:  `filter`, `slices`, `pinned` or something similar
- I suggest we rename `selection` into `filter`. This filter can be an array, but may also be a range or function(name).
- Question: should filters for variables be shared over different axes? (I think so), e.g. Putting `sex` on the `color` axis and on the  `column` axis, (which is fine to me), should have the same selection otherwise nonsense will be drawn.
- We should have a js function/object that controls the validity of the mapping object. (setting the slices etcetera)

**Comment by djvanderlaan** [comment]
The following solution has been chosen:

``` js
{
  x: [
    {variable: 'year'}
  ], 
  y: [
    {variable: 'diabetes'}
  ],
  colour: [
    {variable: 'sex', filter: ['total', 'male']}
  ],
  _filter: [
    {variable: 'age', filter: ['total']},
    {variable: 'region', filter: ['amsterdam']}
  ]
}
```

This is now included in the Mapping object
